name: local
description: local package
version: 0.0.1

environment:
  sdk: ^3.4.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
