name: domain
description: domain package

environment:
  sdk: ^3.4.4

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.25.8
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.1
  freezed: ^2.4.3

dependency_overrides:
  intl: 0.18.1
